/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  Admin: () => import('#controllers/admin_controller'),
  Auth: () => import('#controllers/auth_controller'),
  Chat: () => import('#controllers/chat_controller'),
  Conversacion: () => import('#controllers/conversacion_controller'),
  Dispute: () => import('#controllers/dispute_controller'),
  Driver: () => import('#controllers/driver_controller'),
  EmergencyChat: () => import('#controllers/emergency_chat_controller'),
  Emergency: () => import('#controllers/emergency_controller'),
  FavoriteRoute: () => import('#controllers/favorite_route_controller'),
  FraudAlert: () => import('#controllers/fraud_alert_controller'),
  Leader: () => import('#controllers/leader_controller'),
  Mapbox: () => import('#controllers/mapbox_controller'),
  Moderator: () => import('#controllers/moderator_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Notification: () => import('#controllers/notification_controller'),
  Offer: () => import('#controllers/offer_controller'),
  Payment: () => import('#controllers/payment_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Report: () => import('#controllers/report_controller'),
  Settings: () => import('#controllers/settings_controller'),
  Support: () => import('#controllers/support_controller'),
  Ticket: () => import('#controllers/ticket_controller'),
  Trip: () => import('#controllers/trip_controller'),
}
