/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="../../adonisrc.ts" />
/// <reference path="../../config/antifraude.ts" />
/// <reference path="../../config/auth.ts" />
/// <reference path="../../config/hash.ts" />
/// <reference path="../../config/logger.ts" />
/// <reference path="../../config/openapi.ts" />
/// <reference path="../../config/reservations.ts" />
/// <reference path="../../config/sentry.ts" />
