/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'auth.auth.register': {
    methods: ["POST"],
    pattern: '/api/auth/register',
    tokens: [{"old":"/api/auth/register","type":0,"val":"api","end":""},{"old":"/api/auth/register","type":0,"val":"auth","end":""},{"old":"/api/auth/register","type":0,"val":"register","end":""}],
    types: placeholder as Registry['auth.auth.register']['types'],
  },
  'auth.auth.login': {
    methods: ["POST"],
    pattern: '/api/auth/login',
    tokens: [{"old":"/api/auth/login","type":0,"val":"api","end":""},{"old":"/api/auth/login","type":0,"val":"auth","end":""},{"old":"/api/auth/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['auth.auth.login']['types'],
  },
  'auth.auth.refresh_token': {
    methods: ["POST"],
    pattern: '/api/auth/refresh-token',
    tokens: [{"old":"/api/auth/refresh-token","type":0,"val":"api","end":""},{"old":"/api/auth/refresh-token","type":0,"val":"auth","end":""},{"old":"/api/auth/refresh-token","type":0,"val":"refresh-token","end":""}],
    types: placeholder as Registry['auth.auth.refresh_token']['types'],
  },
  'auth.auth.logout': {
    methods: ["POST"],
    pattern: '/api/auth/logout',
    tokens: [{"old":"/api/auth/logout","type":0,"val":"api","end":""},{"old":"/api/auth/logout","type":0,"val":"auth","end":""},{"old":"/api/auth/logout","type":0,"val":"logout","end":""}],
    types: placeholder as Registry['auth.auth.logout']['types'],
  },
  'users.profile.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/users/profile',
    tokens: [{"old":"/api/users/profile","type":0,"val":"api","end":""},{"old":"/api/users/profile","type":0,"val":"users","end":""},{"old":"/api/users/profile","type":0,"val":"profile","end":""}],
    types: placeholder as Registry['users.profile.show']['types'],
  },
  'users.profile.update': {
    methods: ["PUT"],
    pattern: '/api/users/profile',
    tokens: [{"old":"/api/users/profile","type":0,"val":"api","end":""},{"old":"/api/users/profile","type":0,"val":"users","end":""},{"old":"/api/users/profile","type":0,"val":"profile","end":""}],
    types: placeholder as Registry['users.profile.update']['types'],
  },
  'users.profile.avatar': {
    methods: ["POST"],
    pattern: '/api/users/avatar',
    tokens: [{"old":"/api/users/avatar","type":0,"val":"api","end":""},{"old":"/api/users/avatar","type":0,"val":"users","end":""},{"old":"/api/users/avatar","type":0,"val":"avatar","end":""}],
    types: placeholder as Registry['users.profile.avatar']['types'],
  },
  'users.profile.update_fcm_token': {
    methods: ["PUT"],
    pattern: '/api/users/fcm-token',
    tokens: [{"old":"/api/users/fcm-token","type":0,"val":"api","end":""},{"old":"/api/users/fcm-token","type":0,"val":"users","end":""},{"old":"/api/users/fcm-token","type":0,"val":"fcm-token","end":""}],
    types: placeholder as Registry['users.profile.update_fcm_token']['types'],
  },
  'drivers.driver.status': {
    methods: ["PUT"],
    pattern: '/api/drivers/status',
    tokens: [{"old":"/api/drivers/status","type":0,"val":"api","end":""},{"old":"/api/drivers/status","type":0,"val":"drivers","end":""},{"old":"/api/drivers/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['drivers.driver.status']['types'],
  },
  'drivers.driver.earnings': {
    methods: ["GET","HEAD"],
    pattern: '/api/drivers/earnings',
    tokens: [{"old":"/api/drivers/earnings","type":0,"val":"api","end":""},{"old":"/api/drivers/earnings","type":0,"val":"drivers","end":""},{"old":"/api/drivers/earnings","type":0,"val":"earnings","end":""}],
    types: placeholder as Registry['drivers.driver.earnings']['types'],
  },
  'drivers.driver.stats': {
    methods: ["GET","HEAD"],
    pattern: '/api/drivers/stats',
    tokens: [{"old":"/api/drivers/stats","type":0,"val":"api","end":""},{"old":"/api/drivers/stats","type":0,"val":"drivers","end":""},{"old":"/api/drivers/stats","type":0,"val":"stats","end":""}],
    types: placeholder as Registry['drivers.driver.stats']['types'],
  },
  'drivers.driver.today_stats': {
    methods: ["GET","HEAD"],
    pattern: '/api/drivers/today-stats',
    tokens: [{"old":"/api/drivers/today-stats","type":0,"val":"api","end":""},{"old":"/api/drivers/today-stats","type":0,"val":"drivers","end":""},{"old":"/api/drivers/today-stats","type":0,"val":"today-stats","end":""}],
    types: placeholder as Registry['drivers.driver.today_stats']['types'],
  },
  'drivers.driver.earnings_history': {
    methods: ["GET","HEAD"],
    pattern: '/api/drivers/earnings/history',
    tokens: [{"old":"/api/drivers/earnings/history","type":0,"val":"api","end":""},{"old":"/api/drivers/earnings/history","type":0,"val":"drivers","end":""},{"old":"/api/drivers/earnings/history","type":0,"val":"earnings","end":""},{"old":"/api/drivers/earnings/history","type":0,"val":"history","end":""}],
    types: placeholder as Registry['drivers.driver.earnings_history']['types'],
  },
  'drivers.driver.earnings_pdf': {
    methods: ["GET","HEAD"],
    pattern: '/api/drivers/earnings/pdf',
    tokens: [{"old":"/api/drivers/earnings/pdf","type":0,"val":"api","end":""},{"old":"/api/drivers/earnings/pdf","type":0,"val":"drivers","end":""},{"old":"/api/drivers/earnings/pdf","type":0,"val":"earnings","end":""},{"old":"/api/drivers/earnings/pdf","type":0,"val":"pdf","end":""}],
    types: placeholder as Registry['drivers.driver.earnings_pdf']['types'],
  },
  'drivers.driver.vehicle_photo': {
    methods: ["POST"],
    pattern: '/api/drivers/vehicle-photo',
    tokens: [{"old":"/api/drivers/vehicle-photo","type":0,"val":"api","end":""},{"old":"/api/drivers/vehicle-photo","type":0,"val":"drivers","end":""},{"old":"/api/drivers/vehicle-photo","type":0,"val":"vehicle-photo","end":""}],
    types: placeholder as Registry['drivers.driver.vehicle_photo']['types'],
  },
  'drivers.driver.location': {
    methods: ["PUT"],
    pattern: '/api/drivers/location',
    tokens: [{"old":"/api/drivers/location","type":0,"val":"api","end":""},{"old":"/api/drivers/location","type":0,"val":"drivers","end":""},{"old":"/api/drivers/location","type":0,"val":"location","end":""}],
    types: placeholder as Registry['drivers.driver.location']['types'],
  },
  'drivers.driver.driver_photo': {
    methods: ["POST"],
    pattern: '/api/drivers/driver-photo',
    tokens: [{"old":"/api/drivers/driver-photo","type":0,"val":"api","end":""},{"old":"/api/drivers/driver-photo","type":0,"val":"drivers","end":""},{"old":"/api/drivers/driver-photo","type":0,"val":"driver-photo","end":""}],
    types: placeholder as Registry['drivers.driver.driver_photo']['types'],
  },
  'drivers.driver.upload_cedula': {
    methods: ["POST"],
    pattern: '/api/drivers/verification/cedula',
    tokens: [{"old":"/api/drivers/verification/cedula","type":0,"val":"api","end":""},{"old":"/api/drivers/verification/cedula","type":0,"val":"drivers","end":""},{"old":"/api/drivers/verification/cedula","type":0,"val":"verification","end":""},{"old":"/api/drivers/verification/cedula","type":0,"val":"cedula","end":""}],
    types: placeholder as Registry['drivers.driver.upload_cedula']['types'],
  },
  'drivers.driver.upload_licencia': {
    methods: ["POST"],
    pattern: '/api/drivers/verification/licencia',
    tokens: [{"old":"/api/drivers/verification/licencia","type":0,"val":"api","end":""},{"old":"/api/drivers/verification/licencia","type":0,"val":"drivers","end":""},{"old":"/api/drivers/verification/licencia","type":0,"val":"verification","end":""},{"old":"/api/drivers/verification/licencia","type":0,"val":"licencia","end":""}],
    types: placeholder as Registry['drivers.driver.upload_licencia']['types'],
  },
  'drivers.driver.upload_vehiculo': {
    methods: ["POST"],
    pattern: '/api/drivers/verification/vehiculo',
    tokens: [{"old":"/api/drivers/verification/vehiculo","type":0,"val":"api","end":""},{"old":"/api/drivers/verification/vehiculo","type":0,"val":"drivers","end":""},{"old":"/api/drivers/verification/vehiculo","type":0,"val":"verification","end":""},{"old":"/api/drivers/verification/vehiculo","type":0,"val":"vehiculo","end":""}],
    types: placeholder as Registry['drivers.driver.upload_vehiculo']['types'],
  },
  'trips.trip.request': {
    methods: ["POST"],
    pattern: '/api/trips/request',
    tokens: [{"old":"/api/trips/request","type":0,"val":"api","end":""},{"old":"/api/trips/request","type":0,"val":"trips","end":""},{"old":"/api/trips/request","type":0,"val":"request","end":""}],
    types: placeholder as Registry['trips.trip.request']['types'],
  },
  'trips.trip.nearby': {
    methods: ["GET","HEAD"],
    pattern: '/api/trips/nearby',
    tokens: [{"old":"/api/trips/nearby","type":0,"val":"api","end":""},{"old":"/api/trips/nearby","type":0,"val":"trips","end":""},{"old":"/api/trips/nearby","type":0,"val":"nearby","end":""}],
    types: placeholder as Registry['trips.trip.nearby']['types'],
  },
  'trips.trip.active': {
    methods: ["GET","HEAD"],
    pattern: '/api/trips/active',
    tokens: [{"old":"/api/trips/active","type":0,"val":"api","end":""},{"old":"/api/trips/active","type":0,"val":"trips","end":""},{"old":"/api/trips/active","type":0,"val":"active","end":""}],
    types: placeholder as Registry['trips.trip.active']['types'],
  },
  'trips.trip.history': {
    methods: ["GET","HEAD"],
    pattern: '/api/trips/history',
    tokens: [{"old":"/api/trips/history","type":0,"val":"api","end":""},{"old":"/api/trips/history","type":0,"val":"trips","end":""},{"old":"/api/trips/history","type":0,"val":"history","end":""}],
    types: placeholder as Registry['trips.trip.history']['types'],
  },
  'trips.trip.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/trips/:id',
    tokens: [{"old":"/api/trips/:id","type":0,"val":"api","end":""},{"old":"/api/trips/:id","type":0,"val":"trips","end":""},{"old":"/api/trips/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['trips.trip.show']['types'],
  },
  'trips.trip.accept': {
    methods: ["POST"],
    pattern: '/api/trips/:id/accept',
    tokens: [{"old":"/api/trips/:id/accept","type":0,"val":"api","end":""},{"old":"/api/trips/:id/accept","type":0,"val":"trips","end":""},{"old":"/api/trips/:id/accept","type":1,"val":"id","end":""},{"old":"/api/trips/:id/accept","type":0,"val":"accept","end":""}],
    types: placeholder as Registry['trips.trip.accept']['types'],
  },
  'trips.trip.decline': {
    methods: ["POST"],
    pattern: '/api/trips/:id/decline',
    tokens: [{"old":"/api/trips/:id/decline","type":0,"val":"api","end":""},{"old":"/api/trips/:id/decline","type":0,"val":"trips","end":""},{"old":"/api/trips/:id/decline","type":1,"val":"id","end":""},{"old":"/api/trips/:id/decline","type":0,"val":"decline","end":""}],
    types: placeholder as Registry['trips.trip.decline']['types'],
  },
  'trips.trip.start_trip': {
    methods: ["POST"],
    pattern: '/api/trips/:id/start-trip',
    tokens: [{"old":"/api/trips/:id/start-trip","type":0,"val":"api","end":""},{"old":"/api/trips/:id/start-trip","type":0,"val":"trips","end":""},{"old":"/api/trips/:id/start-trip","type":1,"val":"id","end":""},{"old":"/api/trips/:id/start-trip","type":0,"val":"start-trip","end":""}],
    types: placeholder as Registry['trips.trip.start_trip']['types'],
  },
  'trips.trip.complete': {
    methods: ["POST"],
    pattern: '/api/trips/:id/complete',
    tokens: [{"old":"/api/trips/:id/complete","type":0,"val":"api","end":""},{"old":"/api/trips/:id/complete","type":0,"val":"trips","end":""},{"old":"/api/trips/:id/complete","type":1,"val":"id","end":""},{"old":"/api/trips/:id/complete","type":0,"val":"complete","end":""}],
    types: placeholder as Registry['trips.trip.complete']['types'],
  },
  'trips.trip.finalize': {
    methods: ["POST"],
    pattern: '/api/trips/:id/finalize',
    tokens: [{"old":"/api/trips/:id/finalize","type":0,"val":"api","end":""},{"old":"/api/trips/:id/finalize","type":0,"val":"trips","end":""},{"old":"/api/trips/:id/finalize","type":1,"val":"id","end":""},{"old":"/api/trips/:id/finalize","type":0,"val":"finalize","end":""}],
    types: placeholder as Registry['trips.trip.finalize']['types'],
  },
  'trips.trip.cancel': {
    methods: ["POST"],
    pattern: '/api/trips/:id/cancel',
    tokens: [{"old":"/api/trips/:id/cancel","type":0,"val":"api","end":""},{"old":"/api/trips/:id/cancel","type":0,"val":"trips","end":""},{"old":"/api/trips/:id/cancel","type":1,"val":"id","end":""},{"old":"/api/trips/:id/cancel","type":0,"val":"cancel","end":""}],
    types: placeholder as Registry['trips.trip.cancel']['types'],
  },
  'trips.trip.request_cancellation': {
    methods: ["POST"],
    pattern: '/api/trips/:id/request-cancellation',
    tokens: [{"old":"/api/trips/:id/request-cancellation","type":0,"val":"api","end":""},{"old":"/api/trips/:id/request-cancellation","type":0,"val":"trips","end":""},{"old":"/api/trips/:id/request-cancellation","type":1,"val":"id","end":""},{"old":"/api/trips/:id/request-cancellation","type":0,"val":"request-cancellation","end":""}],
    types: placeholder as Registry['trips.trip.request_cancellation']['types'],
  },
  'trips.trip.rate': {
    methods: ["POST"],
    pattern: '/api/trips/:id/rate',
    tokens: [{"old":"/api/trips/:id/rate","type":0,"val":"api","end":""},{"old":"/api/trips/:id/rate","type":0,"val":"trips","end":""},{"old":"/api/trips/:id/rate","type":1,"val":"id","end":""},{"old":"/api/trips/:id/rate","type":0,"val":"rate","end":""}],
    types: placeholder as Registry['trips.trip.rate']['types'],
  },
  'trips.trip.delivery_photo': {
    methods: ["POST"],
    pattern: '/api/trips/:id/delivery-photo',
    tokens: [{"old":"/api/trips/:id/delivery-photo","type":0,"val":"api","end":""},{"old":"/api/trips/:id/delivery-photo","type":0,"val":"trips","end":""},{"old":"/api/trips/:id/delivery-photo","type":1,"val":"id","end":""},{"old":"/api/trips/:id/delivery-photo","type":0,"val":"delivery-photo","end":""}],
    types: placeholder as Registry['trips.trip.delivery_photo']['types'],
  },
  'trips.chat.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/trips/:id/chat',
    tokens: [{"old":"/api/trips/:id/chat","type":0,"val":"api","end":""},{"old":"/api/trips/:id/chat","type":0,"val":"trips","end":""},{"old":"/api/trips/:id/chat","type":1,"val":"id","end":""},{"old":"/api/trips/:id/chat","type":0,"val":"chat","end":""}],
    types: placeholder as Registry['trips.chat.index']['types'],
  },
  'trips.chat.store': {
    methods: ["POST"],
    pattern: '/api/trips/:id/chat',
    tokens: [{"old":"/api/trips/:id/chat","type":0,"val":"api","end":""},{"old":"/api/trips/:id/chat","type":0,"val":"trips","end":""},{"old":"/api/trips/:id/chat","type":1,"val":"id","end":""},{"old":"/api/trips/:id/chat","type":0,"val":"chat","end":""}],
    types: placeholder as Registry['trips.chat.store']['types'],
  },
  'trips.dispute.store': {
    methods: ["POST"],
    pattern: '/api/trips/:id/dispute',
    tokens: [{"old":"/api/trips/:id/dispute","type":0,"val":"api","end":""},{"old":"/api/trips/:id/dispute","type":0,"val":"trips","end":""},{"old":"/api/trips/:id/dispute","type":1,"val":"id","end":""},{"old":"/api/trips/:id/dispute","type":0,"val":"dispute","end":""}],
    types: placeholder as Registry['trips.dispute.store']['types'],
  },
  'trips.dispute.appeal': {
    methods: ["POST"],
    pattern: '/api/trips/:id/dispute/appeal',
    tokens: [{"old":"/api/trips/:id/dispute/appeal","type":0,"val":"api","end":""},{"old":"/api/trips/:id/dispute/appeal","type":0,"val":"trips","end":""},{"old":"/api/trips/:id/dispute/appeal","type":1,"val":"id","end":""},{"old":"/api/trips/:id/dispute/appeal","type":0,"val":"dispute","end":""},{"old":"/api/trips/:id/dispute/appeal","type":0,"val":"appeal","end":""}],
    types: placeholder as Registry['trips.dispute.appeal']['types'],
  },
  'trips.dispute.upload_support': {
    methods: ["POST"],
    pattern: '/api/trips/:id/dispute/support',
    tokens: [{"old":"/api/trips/:id/dispute/support","type":0,"val":"api","end":""},{"old":"/api/trips/:id/dispute/support","type":0,"val":"trips","end":""},{"old":"/api/trips/:id/dispute/support","type":1,"val":"id","end":""},{"old":"/api/trips/:id/dispute/support","type":0,"val":"dispute","end":""},{"old":"/api/trips/:id/dispute/support","type":0,"val":"support","end":""}],
    types: placeholder as Registry['trips.dispute.upload_support']['types'],
  },
  'trips.offer.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/trips/:id/offers',
    tokens: [{"old":"/api/trips/:id/offers","type":0,"val":"api","end":""},{"old":"/api/trips/:id/offers","type":0,"val":"trips","end":""},{"old":"/api/trips/:id/offers","type":1,"val":"id","end":""},{"old":"/api/trips/:id/offers","type":0,"val":"offers","end":""}],
    types: placeholder as Registry['trips.offer.index']['types'],
  },
  'trips.offer.store': {
    methods: ["POST"],
    pattern: '/api/trips/:id/offers',
    tokens: [{"old":"/api/trips/:id/offers","type":0,"val":"api","end":""},{"old":"/api/trips/:id/offers","type":0,"val":"trips","end":""},{"old":"/api/trips/:id/offers","type":1,"val":"id","end":""},{"old":"/api/trips/:id/offers","type":0,"val":"offers","end":""}],
    types: placeholder as Registry['trips.offer.store']['types'],
  },
  'trips.offer.accept': {
    methods: ["POST"],
    pattern: '/api/trips/:id/offers/:offerId/accept',
    tokens: [{"old":"/api/trips/:id/offers/:offerId/accept","type":0,"val":"api","end":""},{"old":"/api/trips/:id/offers/:offerId/accept","type":0,"val":"trips","end":""},{"old":"/api/trips/:id/offers/:offerId/accept","type":1,"val":"id","end":""},{"old":"/api/trips/:id/offers/:offerId/accept","type":0,"val":"offers","end":""},{"old":"/api/trips/:id/offers/:offerId/accept","type":1,"val":"offerId","end":""},{"old":"/api/trips/:id/offers/:offerId/accept","type":0,"val":"accept","end":""}],
    types: placeholder as Registry['trips.offer.accept']['types'],
  },
  'trips.offer.reject': {
    methods: ["POST"],
    pattern: '/api/trips/:id/offers/:offerId/reject',
    tokens: [{"old":"/api/trips/:id/offers/:offerId/reject","type":0,"val":"api","end":""},{"old":"/api/trips/:id/offers/:offerId/reject","type":0,"val":"trips","end":""},{"old":"/api/trips/:id/offers/:offerId/reject","type":1,"val":"id","end":""},{"old":"/api/trips/:id/offers/:offerId/reject","type":0,"val":"offers","end":""},{"old":"/api/trips/:id/offers/:offerId/reject","type":1,"val":"offerId","end":""},{"old":"/api/trips/:id/offers/:offerId/reject","type":0,"val":"reject","end":""}],
    types: placeholder as Registry['trips.offer.reject']['types'],
  },
  'trips.offer.confirm_arrival': {
    methods: ["POST"],
    pattern: '/api/trips/:id/confirm-arrival',
    tokens: [{"old":"/api/trips/:id/confirm-arrival","type":0,"val":"api","end":""},{"old":"/api/trips/:id/confirm-arrival","type":0,"val":"trips","end":""},{"old":"/api/trips/:id/confirm-arrival","type":1,"val":"id","end":""},{"old":"/api/trips/:id/confirm-arrival","type":0,"val":"confirm-arrival","end":""}],
    types: placeholder as Registry['trips.offer.confirm_arrival']['types'],
  },
  'trips.offer.confirm_pickup': {
    methods: ["POST"],
    pattern: '/api/trips/:id/confirm-pickup',
    tokens: [{"old":"/api/trips/:id/confirm-pickup","type":0,"val":"api","end":""},{"old":"/api/trips/:id/confirm-pickup","type":0,"val":"trips","end":""},{"old":"/api/trips/:id/confirm-pickup","type":1,"val":"id","end":""},{"old":"/api/trips/:id/confirm-pickup","type":0,"val":"confirm-pickup","end":""}],
    types: placeholder as Registry['trips.offer.confirm_pickup']['types'],
  },
  'trips.report.store': {
    methods: ["POST"],
    pattern: '/api/trips/:id/report',
    tokens: [{"old":"/api/trips/:id/report","type":0,"val":"api","end":""},{"old":"/api/trips/:id/report","type":0,"val":"trips","end":""},{"old":"/api/trips/:id/report","type":1,"val":"id","end":""},{"old":"/api/trips/:id/report","type":0,"val":"report","end":""}],
    types: placeholder as Registry['trips.report.store']['types'],
  },
  'notifications.notification.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/notifications',
    tokens: [{"old":"/api/notifications","type":0,"val":"api","end":""},{"old":"/api/notifications","type":0,"val":"notifications","end":""}],
    types: placeholder as Registry['notifications.notification.index']['types'],
  },
  'notifications.notification.read': {
    methods: ["PUT"],
    pattern: '/api/notifications/:id/read',
    tokens: [{"old":"/api/notifications/:id/read","type":0,"val":"api","end":""},{"old":"/api/notifications/:id/read","type":0,"val":"notifications","end":""},{"old":"/api/notifications/:id/read","type":1,"val":"id","end":""},{"old":"/api/notifications/:id/read","type":0,"val":"read","end":""}],
    types: placeholder as Registry['notifications.notification.read']['types'],
  },
  'admin.admin.dashboard': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/dashboard',
    tokens: [{"old":"/api/admin/dashboard","type":0,"val":"api","end":""},{"old":"/api/admin/dashboard","type":0,"val":"admin","end":""},{"old":"/api/admin/dashboard","type":0,"val":"dashboard","end":""}],
    types: placeholder as Registry['admin.admin.dashboard']['types'],
  },
  'admin.admin.users': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/users',
    tokens: [{"old":"/api/admin/users","type":0,"val":"api","end":""},{"old":"/api/admin/users","type":0,"val":"admin","end":""},{"old":"/api/admin/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['admin.admin.users']['types'],
  },
  'admin.admin.drivers': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/drivers',
    tokens: [{"old":"/api/admin/drivers","type":0,"val":"api","end":""},{"old":"/api/admin/drivers","type":0,"val":"admin","end":""},{"old":"/api/admin/drivers","type":0,"val":"drivers","end":""}],
    types: placeholder as Registry['admin.admin.drivers']['types'],
  },
  'admin.admin.trips': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/trips',
    tokens: [{"old":"/api/admin/trips","type":0,"val":"api","end":""},{"old":"/api/admin/trips","type":0,"val":"admin","end":""},{"old":"/api/admin/trips","type":0,"val":"trips","end":""}],
    types: placeholder as Registry['admin.admin.trips']['types'],
  },
  'admin.admin.earnings': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/earnings',
    tokens: [{"old":"/api/admin/earnings","type":0,"val":"api","end":""},{"old":"/api/admin/earnings","type":0,"val":"admin","end":""},{"old":"/api/admin/earnings","type":0,"val":"earnings","end":""}],
    types: placeholder as Registry['admin.admin.earnings']['types'],
  },
  'admin.admin.update_user': {
    methods: ["PUT"],
    pattern: '/api/admin/users/:id',
    tokens: [{"old":"/api/admin/users/:id","type":0,"val":"api","end":""},{"old":"/api/admin/users/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/users/:id","type":0,"val":"users","end":""},{"old":"/api/admin/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.admin.update_user']['types'],
  },
  'admin.admin.toggle_suspend_user': {
    methods: ["PUT"],
    pattern: '/api/admin/users/:id/suspend',
    tokens: [{"old":"/api/admin/users/:id/suspend","type":0,"val":"api","end":""},{"old":"/api/admin/users/:id/suspend","type":0,"val":"admin","end":""},{"old":"/api/admin/users/:id/suspend","type":0,"val":"users","end":""},{"old":"/api/admin/users/:id/suspend","type":1,"val":"id","end":""},{"old":"/api/admin/users/:id/suspend","type":0,"val":"suspend","end":""}],
    types: placeholder as Registry['admin.admin.toggle_suspend_user']['types'],
  },
  'admin.admin.upload_user_avatar': {
    methods: ["PUT"],
    pattern: '/api/admin/users/:id/avatar',
    tokens: [{"old":"/api/admin/users/:id/avatar","type":0,"val":"api","end":""},{"old":"/api/admin/users/:id/avatar","type":0,"val":"admin","end":""},{"old":"/api/admin/users/:id/avatar","type":0,"val":"users","end":""},{"old":"/api/admin/users/:id/avatar","type":1,"val":"id","end":""},{"old":"/api/admin/users/:id/avatar","type":0,"val":"avatar","end":""}],
    types: placeholder as Registry['admin.admin.upload_user_avatar']['types'],
  },
  'admin.admin.delete_user': {
    methods: ["DELETE"],
    pattern: '/api/admin/users/:id',
    tokens: [{"old":"/api/admin/users/:id","type":0,"val":"api","end":""},{"old":"/api/admin/users/:id","type":0,"val":"admin","end":""},{"old":"/api/admin/users/:id","type":0,"val":"users","end":""},{"old":"/api/admin/users/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['admin.admin.delete_user']['types'],
  },
  'admin.admin.profile': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/profile',
    tokens: [{"old":"/api/admin/profile","type":0,"val":"api","end":""},{"old":"/api/admin/profile","type":0,"val":"admin","end":""},{"old":"/api/admin/profile","type":0,"val":"profile","end":""}],
    types: placeholder as Registry['admin.admin.profile']['types'],
  },
  'admin.admin.emergencies': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/emergencies',
    tokens: [{"old":"/api/admin/emergencies","type":0,"val":"api","end":""},{"old":"/api/admin/emergencies","type":0,"val":"admin","end":""},{"old":"/api/admin/emergencies","type":0,"val":"emergencies","end":""}],
    types: placeholder as Registry['admin.admin.emergencies']['types'],
  },
  'admin.admin.resolve_emergency': {
    methods: ["PUT"],
    pattern: '/api/admin/emergencies/:id/resolve',
    tokens: [{"old":"/api/admin/emergencies/:id/resolve","type":0,"val":"api","end":""},{"old":"/api/admin/emergencies/:id/resolve","type":0,"val":"admin","end":""},{"old":"/api/admin/emergencies/:id/resolve","type":0,"val":"emergencies","end":""},{"old":"/api/admin/emergencies/:id/resolve","type":1,"val":"id","end":""},{"old":"/api/admin/emergencies/:id/resolve","type":0,"val":"resolve","end":""}],
    types: placeholder as Registry['admin.admin.resolve_emergency']['types'],
  },
  'admin.admin.update_profile': {
    methods: ["PUT"],
    pattern: '/api/admin/profile',
    tokens: [{"old":"/api/admin/profile","type":0,"val":"api","end":""},{"old":"/api/admin/profile","type":0,"val":"admin","end":""},{"old":"/api/admin/profile","type":0,"val":"profile","end":""}],
    types: placeholder as Registry['admin.admin.update_profile']['types'],
  },
  'admin.admin.upload_profile_avatar': {
    methods: ["POST"],
    pattern: '/api/admin/profile/avatar',
    tokens: [{"old":"/api/admin/profile/avatar","type":0,"val":"api","end":""},{"old":"/api/admin/profile/avatar","type":0,"val":"admin","end":""},{"old":"/api/admin/profile/avatar","type":0,"val":"profile","end":""},{"old":"/api/admin/profile/avatar","type":0,"val":"avatar","end":""}],
    types: placeholder as Registry['admin.admin.upload_profile_avatar']['types'],
  },
  'admin.admin.conductor_debt': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/commissions',
    tokens: [{"old":"/api/admin/commissions","type":0,"val":"api","end":""},{"old":"/api/admin/commissions","type":0,"val":"admin","end":""},{"old":"/api/admin/commissions","type":0,"val":"commissions","end":""}],
    types: placeholder as Registry['admin.admin.conductor_debt']['types'],
  },
  'admin.admin.mark_commission_paid': {
    methods: ["PUT"],
    pattern: '/api/admin/commissions/:conductorId/paid',
    tokens: [{"old":"/api/admin/commissions/:conductorId/paid","type":0,"val":"api","end":""},{"old":"/api/admin/commissions/:conductorId/paid","type":0,"val":"admin","end":""},{"old":"/api/admin/commissions/:conductorId/paid","type":0,"val":"commissions","end":""},{"old":"/api/admin/commissions/:conductorId/paid","type":1,"val":"conductorId","end":""},{"old":"/api/admin/commissions/:conductorId/paid","type":0,"val":"paid","end":""}],
    types: placeholder as Registry['admin.admin.mark_commission_paid']['types'],
  },
  'admin.admin.commission_history': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/commissions/:conductorId/history',
    tokens: [{"old":"/api/admin/commissions/:conductorId/history","type":0,"val":"api","end":""},{"old":"/api/admin/commissions/:conductorId/history","type":0,"val":"admin","end":""},{"old":"/api/admin/commissions/:conductorId/history","type":0,"val":"commissions","end":""},{"old":"/api/admin/commissions/:conductorId/history","type":1,"val":"conductorId","end":""},{"old":"/api/admin/commissions/:conductorId/history","type":0,"val":"history","end":""}],
    types: placeholder as Registry['admin.admin.commission_history']['types'],
  },
  'admin.admin.reports': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/reports',
    tokens: [{"old":"/api/admin/reports","type":0,"val":"api","end":""},{"old":"/api/admin/reports","type":0,"val":"admin","end":""},{"old":"/api/admin/reports","type":0,"val":"reports","end":""}],
    types: placeholder as Registry['admin.admin.reports']['types'],
  },
  'admin.admin.resolve_report': {
    methods: ["PUT"],
    pattern: '/api/admin/reports/:id/resolve',
    tokens: [{"old":"/api/admin/reports/:id/resolve","type":0,"val":"api","end":""},{"old":"/api/admin/reports/:id/resolve","type":0,"val":"admin","end":""},{"old":"/api/admin/reports/:id/resolve","type":0,"val":"reports","end":""},{"old":"/api/admin/reports/:id/resolve","type":1,"val":"id","end":""},{"old":"/api/admin/reports/:id/resolve","type":0,"val":"resolve","end":""}],
    types: placeholder as Registry['admin.admin.resolve_report']['types'],
  },
  'admin.admin.disputes': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/disputes',
    tokens: [{"old":"/api/admin/disputes","type":0,"val":"api","end":""},{"old":"/api/admin/disputes","type":0,"val":"admin","end":""},{"old":"/api/admin/disputes","type":0,"val":"disputes","end":""}],
    types: placeholder as Registry['admin.admin.disputes']['types'],
  },
  'admin.admin.resolve_dispute': {
    methods: ["PUT"],
    pattern: '/api/admin/disputes/:id/resolve',
    tokens: [{"old":"/api/admin/disputes/:id/resolve","type":0,"val":"api","end":""},{"old":"/api/admin/disputes/:id/resolve","type":0,"val":"admin","end":""},{"old":"/api/admin/disputes/:id/resolve","type":0,"val":"disputes","end":""},{"old":"/api/admin/disputes/:id/resolve","type":1,"val":"id","end":""},{"old":"/api/admin/disputes/:id/resolve","type":0,"val":"resolve","end":""}],
    types: placeholder as Registry['admin.admin.resolve_dispute']['types'],
  },
  'admin.admin.clear_debt': {
    methods: ["PUT"],
    pattern: '/api/admin/users/:id/clear-debt',
    tokens: [{"old":"/api/admin/users/:id/clear-debt","type":0,"val":"api","end":""},{"old":"/api/admin/users/:id/clear-debt","type":0,"val":"admin","end":""},{"old":"/api/admin/users/:id/clear-debt","type":0,"val":"users","end":""},{"old":"/api/admin/users/:id/clear-debt","type":1,"val":"id","end":""},{"old":"/api/admin/users/:id/clear-debt","type":0,"val":"clear-debt","end":""}],
    types: placeholder as Registry['admin.admin.clear_debt']['types'],
  },
  'admin.admin.pending_verifications': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/verifications',
    tokens: [{"old":"/api/admin/verifications","type":0,"val":"api","end":""},{"old":"/api/admin/verifications","type":0,"val":"admin","end":""},{"old":"/api/admin/verifications","type":0,"val":"verifications","end":""}],
    types: placeholder as Registry['admin.admin.pending_verifications']['types'],
  },
  'admin.admin.approve_driver': {
    methods: ["PUT"],
    pattern: '/api/admin/verifications/:conductorId/approve',
    tokens: [{"old":"/api/admin/verifications/:conductorId/approve","type":0,"val":"api","end":""},{"old":"/api/admin/verifications/:conductorId/approve","type":0,"val":"admin","end":""},{"old":"/api/admin/verifications/:conductorId/approve","type":0,"val":"verifications","end":""},{"old":"/api/admin/verifications/:conductorId/approve","type":1,"val":"conductorId","end":""},{"old":"/api/admin/verifications/:conductorId/approve","type":0,"val":"approve","end":""}],
    types: placeholder as Registry['admin.admin.approve_driver']['types'],
  },
  'admin.admin.reject_driver': {
    methods: ["PUT"],
    pattern: '/api/admin/verifications/:conductorId/reject',
    tokens: [{"old":"/api/admin/verifications/:conductorId/reject","type":0,"val":"api","end":""},{"old":"/api/admin/verifications/:conductorId/reject","type":0,"val":"admin","end":""},{"old":"/api/admin/verifications/:conductorId/reject","type":0,"val":"verifications","end":""},{"old":"/api/admin/verifications/:conductorId/reject","type":1,"val":"conductorId","end":""},{"old":"/api/admin/verifications/:conductorId/reject","type":0,"val":"reject","end":""}],
    types: placeholder as Registry['admin.admin.reject_driver']['types'],
  },
  'admin.admin.pending_payments': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/payments/pending',
    tokens: [{"old":"/api/admin/payments/pending","type":0,"val":"api","end":""},{"old":"/api/admin/payments/pending","type":0,"val":"admin","end":""},{"old":"/api/admin/payments/pending","type":0,"val":"payments","end":""},{"old":"/api/admin/payments/pending","type":0,"val":"pending","end":""}],
    types: placeholder as Registry['admin.admin.pending_payments']['types'],
  },
  'admin.admin.confirm_payment': {
    methods: ["PUT"],
    pattern: '/api/admin/payments/:userId/confirm',
    tokens: [{"old":"/api/admin/payments/:userId/confirm","type":0,"val":"api","end":""},{"old":"/api/admin/payments/:userId/confirm","type":0,"val":"admin","end":""},{"old":"/api/admin/payments/:userId/confirm","type":0,"val":"payments","end":""},{"old":"/api/admin/payments/:userId/confirm","type":1,"val":"userId","end":""},{"old":"/api/admin/payments/:userId/confirm","type":0,"val":"confirm","end":""}],
    types: placeholder as Registry['admin.admin.confirm_payment']['types'],
  },
  'admin.admin.reject_payment': {
    methods: ["PUT"],
    pattern: '/api/admin/payments/:userId/reject',
    tokens: [{"old":"/api/admin/payments/:userId/reject","type":0,"val":"api","end":""},{"old":"/api/admin/payments/:userId/reject","type":0,"val":"admin","end":""},{"old":"/api/admin/payments/:userId/reject","type":0,"val":"payments","end":""},{"old":"/api/admin/payments/:userId/reject","type":1,"val":"userId","end":""},{"old":"/api/admin/payments/:userId/reject","type":0,"val":"reject","end":""}],
    types: placeholder as Registry['admin.admin.reject_payment']['types'],
  },
  'admin.admin.update_config': {
    methods: ["PUT"],
    pattern: '/api/admin/config',
    tokens: [{"old":"/api/admin/config","type":0,"val":"api","end":""},{"old":"/api/admin/config","type":0,"val":"admin","end":""},{"old":"/api/admin/config","type":0,"val":"config","end":""}],
    types: placeholder as Registry['admin.admin.update_config']['types'],
  },
  'admin.admin.update_coverage': {
    methods: ["PUT"],
    pattern: '/api/admin/config/coverage',
    tokens: [{"old":"/api/admin/config/coverage","type":0,"val":"api","end":""},{"old":"/api/admin/config/coverage","type":0,"val":"admin","end":""},{"old":"/api/admin/config/coverage","type":0,"val":"config","end":""},{"old":"/api/admin/config/coverage","type":0,"val":"coverage","end":""}],
    types: placeholder as Registry['admin.admin.update_coverage']['types'],
  },
  'admin.admin.update_banner': {
    methods: ["PUT"],
    pattern: '/api/admin/config/banner',
    tokens: [{"old":"/api/admin/config/banner","type":0,"val":"api","end":""},{"old":"/api/admin/config/banner","type":0,"val":"admin","end":""},{"old":"/api/admin/config/banner","type":0,"val":"config","end":""},{"old":"/api/admin/config/banner","type":0,"val":"banner","end":""}],
    types: placeholder as Registry['admin.admin.update_banner']['types'],
  },
  'admin.admin.assign_moderator': {
    methods: ["PUT"],
    pattern: '/api/admin/users/:id/moderator',
    tokens: [{"old":"/api/admin/users/:id/moderator","type":0,"val":"api","end":""},{"old":"/api/admin/users/:id/moderator","type":0,"val":"admin","end":""},{"old":"/api/admin/users/:id/moderator","type":0,"val":"users","end":""},{"old":"/api/admin/users/:id/moderator","type":1,"val":"id","end":""},{"old":"/api/admin/users/:id/moderator","type":0,"val":"moderator","end":""}],
    types: placeholder as Registry['admin.admin.assign_moderator']['types'],
  },
  'admin.admin.assign_leader': {
    methods: ["PUT"],
    pattern: '/api/admin/users/:id/leader',
    tokens: [{"old":"/api/admin/users/:id/leader","type":0,"val":"api","end":""},{"old":"/api/admin/users/:id/leader","type":0,"val":"admin","end":""},{"old":"/api/admin/users/:id/leader","type":0,"val":"users","end":""},{"old":"/api/admin/users/:id/leader","type":1,"val":"id","end":""},{"old":"/api/admin/users/:id/leader","type":0,"val":"leader","end":""}],
    types: placeholder as Registry['admin.admin.assign_leader']['types'],
  },
  'admin.admin.approve_comunicado': {
    methods: ["PUT"],
    pattern: '/api/admin/comunicados/:id/approve',
    tokens: [{"old":"/api/admin/comunicados/:id/approve","type":0,"val":"api","end":""},{"old":"/api/admin/comunicados/:id/approve","type":0,"val":"admin","end":""},{"old":"/api/admin/comunicados/:id/approve","type":0,"val":"comunicados","end":""},{"old":"/api/admin/comunicados/:id/approve","type":1,"val":"id","end":""},{"old":"/api/admin/comunicados/:id/approve","type":0,"val":"approve","end":""}],
    types: placeholder as Registry['admin.admin.approve_comunicado']['types'],
  },
  'admin.admin.reject_comunicado': {
    methods: ["PUT"],
    pattern: '/api/admin/comunicados/:id/reject',
    tokens: [{"old":"/api/admin/comunicados/:id/reject","type":0,"val":"api","end":""},{"old":"/api/admin/comunicados/:id/reject","type":0,"val":"admin","end":""},{"old":"/api/admin/comunicados/:id/reject","type":0,"val":"comunicados","end":""},{"old":"/api/admin/comunicados/:id/reject","type":1,"val":"id","end":""},{"old":"/api/admin/comunicados/:id/reject","type":0,"val":"reject","end":""}],
    types: placeholder as Registry['admin.admin.reject_comunicado']['types'],
  },
  'admin.admin.approve_encuesta': {
    methods: ["PUT"],
    pattern: '/api/admin/encuestas/:id/approve',
    tokens: [{"old":"/api/admin/encuestas/:id/approve","type":0,"val":"api","end":""},{"old":"/api/admin/encuestas/:id/approve","type":0,"val":"admin","end":""},{"old":"/api/admin/encuestas/:id/approve","type":0,"val":"encuestas","end":""},{"old":"/api/admin/encuestas/:id/approve","type":1,"val":"id","end":""},{"old":"/api/admin/encuestas/:id/approve","type":0,"val":"approve","end":""}],
    types: placeholder as Registry['admin.admin.approve_encuesta']['types'],
  },
  'admin.admin.moderator_reports': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/moderator-reports',
    tokens: [{"old":"/api/admin/moderator-reports","type":0,"val":"api","end":""},{"old":"/api/admin/moderator-reports","type":0,"val":"admin","end":""},{"old":"/api/admin/moderator-reports","type":0,"val":"moderator-reports","end":""}],
    types: placeholder as Registry['admin.admin.moderator_reports']['types'],
  },
  'admin.admin.backup_logs': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/backups',
    tokens: [{"old":"/api/admin/backups","type":0,"val":"api","end":""},{"old":"/api/admin/backups","type":0,"val":"admin","end":""},{"old":"/api/admin/backups","type":0,"val":"backups","end":""}],
    types: placeholder as Registry['admin.admin.backup_logs']['types'],
  },
  'admin.admin.manual_backup': {
    methods: ["POST"],
    pattern: '/api/admin/backups/run',
    tokens: [{"old":"/api/admin/backups/run","type":0,"val":"api","end":""},{"old":"/api/admin/backups/run","type":0,"val":"admin","end":""},{"old":"/api/admin/backups/run","type":0,"val":"backups","end":""},{"old":"/api/admin/backups/run","type":0,"val":"run","end":""}],
    types: placeholder as Registry['admin.admin.manual_backup']['types'],
  },
  'admin.admin.cancellation_requests': {
    methods: ["GET","HEAD"],
    pattern: '/api/admin/cancellation-requests',
    tokens: [{"old":"/api/admin/cancellation-requests","type":0,"val":"api","end":""},{"old":"/api/admin/cancellation-requests","type":0,"val":"admin","end":""},{"old":"/api/admin/cancellation-requests","type":0,"val":"cancellation-requests","end":""}],
    types: placeholder as Registry['admin.admin.cancellation_requests']['types'],
  },
  'admin.admin.approve_cancellation': {
    methods: ["POST"],
    pattern: '/api/admin/cancellation-requests/:id/approve',
    tokens: [{"old":"/api/admin/cancellation-requests/:id/approve","type":0,"val":"api","end":""},{"old":"/api/admin/cancellation-requests/:id/approve","type":0,"val":"admin","end":""},{"old":"/api/admin/cancellation-requests/:id/approve","type":0,"val":"cancellation-requests","end":""},{"old":"/api/admin/cancellation-requests/:id/approve","type":1,"val":"id","end":""},{"old":"/api/admin/cancellation-requests/:id/approve","type":0,"val":"approve","end":""}],
    types: placeholder as Registry['admin.admin.approve_cancellation']['types'],
  },
  'admin.admin.reject_cancellation': {
    methods: ["POST"],
    pattern: '/api/admin/cancellation-requests/:id/reject',
    tokens: [{"old":"/api/admin/cancellation-requests/:id/reject","type":0,"val":"api","end":""},{"old":"/api/admin/cancellation-requests/:id/reject","type":0,"val":"admin","end":""},{"old":"/api/admin/cancellation-requests/:id/reject","type":0,"val":"cancellation-requests","end":""},{"old":"/api/admin/cancellation-requests/:id/reject","type":1,"val":"id","end":""},{"old":"/api/admin/cancellation-requests/:id/reject","type":0,"val":"reject","end":""}],
    types: placeholder as Registry['admin.admin.reject_cancellation']['types'],
  },
  'favorites.favorite_route.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/favorites',
    tokens: [{"old":"/api/favorites","type":0,"val":"api","end":""},{"old":"/api/favorites","type":0,"val":"favorites","end":""}],
    types: placeholder as Registry['favorites.favorite_route.index']['types'],
  },
  'favorites.favorite_route.store': {
    methods: ["POST"],
    pattern: '/api/favorites',
    tokens: [{"old":"/api/favorites","type":0,"val":"api","end":""},{"old":"/api/favorites","type":0,"val":"favorites","end":""}],
    types: placeholder as Registry['favorites.favorite_route.store']['types'],
  },
  'favorites.favorite_route.destroy': {
    methods: ["DELETE"],
    pattern: '/api/favorites/:id',
    tokens: [{"old":"/api/favorites/:id","type":0,"val":"api","end":""},{"old":"/api/favorites/:id","type":0,"val":"favorites","end":""},{"old":"/api/favorites/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['favorites.favorite_route.destroy']['types'],
  },
  'support.support.help': {
    methods: ["GET","HEAD"],
    pattern: '/api/support/help',
    tokens: [{"old":"/api/support/help","type":0,"val":"api","end":""},{"old":"/api/support/help","type":0,"val":"support","end":""},{"old":"/api/support/help","type":0,"val":"help","end":""}],
    types: placeholder as Registry['support.support.help']['types'],
  },
  'support.support.emergency': {
    methods: ["GET","HEAD"],
    pattern: '/api/support/emergency',
    tokens: [{"old":"/api/support/emergency","type":0,"val":"api","end":""},{"old":"/api/support/emergency","type":0,"val":"support","end":""},{"old":"/api/support/emergency","type":0,"val":"emergency","end":""}],
    types: placeholder as Registry['support.support.emergency']['types'],
  },
  'disputes.dispute.store_root': {
    methods: ["POST"],
    pattern: '/api/disputes',
    tokens: [{"old":"/api/disputes","type":0,"val":"api","end":""},{"old":"/api/disputes","type":0,"val":"disputes","end":""}],
    types: placeholder as Registry['disputes.dispute.store_root']['types'],
  },
  'disputes.dispute.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/disputes/:id',
    tokens: [{"old":"/api/disputes/:id","type":0,"val":"api","end":""},{"old":"/api/disputes/:id","type":0,"val":"disputes","end":""},{"old":"/api/disputes/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['disputes.dispute.show']['types'],
  },
  'disputes.dispute.submit_version': {
    methods: ["POST"],
    pattern: '/api/disputes/:id/version',
    tokens: [{"old":"/api/disputes/:id/version","type":0,"val":"api","end":""},{"old":"/api/disputes/:id/version","type":0,"val":"disputes","end":""},{"old":"/api/disputes/:id/version","type":1,"val":"id","end":""},{"old":"/api/disputes/:id/version","type":0,"val":"version","end":""}],
    types: placeholder as Registry['disputes.dispute.submit_version']['types'],
  },
  'payment.payment.info': {
    methods: ["GET","HEAD"],
    pattern: '/api/payment/debt',
    tokens: [{"old":"/api/payment/debt","type":0,"val":"api","end":""},{"old":"/api/payment/debt","type":0,"val":"payment","end":""},{"old":"/api/payment/debt","type":0,"val":"debt","end":""}],
    types: placeholder as Registry['payment.payment.info']['types'],
  },
  'payment.payment.upload_proof': {
    methods: ["POST"],
    pattern: '/api/payment/proof',
    tokens: [{"old":"/api/payment/proof","type":0,"val":"api","end":""},{"old":"/api/payment/proof","type":0,"val":"payment","end":""},{"old":"/api/payment/proof","type":0,"val":"proof","end":""}],
    types: placeholder as Registry['payment.payment.upload_proof']['types'],
  },
  'payments.info': {
    methods: ["GET","HEAD"],
    pattern: '/api/payments',
    tokens: [{"old":"/api/payments","type":0,"val":"api","end":""},{"old":"/api/payments","type":0,"val":"payments","end":""}],
    types: placeholder as Registry['payments.info']['types'],
  },
  'settings.settings.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/settings',
    tokens: [{"old":"/api/settings","type":0,"val":"api","end":""},{"old":"/api/settings","type":0,"val":"settings","end":""}],
    types: placeholder as Registry['settings.settings.show']['types'],
  },
  'settings.settings.update': {
    methods: ["PUT"],
    pattern: '/api/settings',
    tokens: [{"old":"/api/settings","type":0,"val":"api","end":""},{"old":"/api/settings","type":0,"val":"settings","end":""}],
    types: placeholder as Registry['settings.settings.update']['types'],
  },
  'mapbox.token': {
    methods: ["GET","HEAD"],
    pattern: '/api/config/mapbox',
    tokens: [{"old":"/api/config/mapbox","type":0,"val":"api","end":""},{"old":"/api/config/mapbox","type":0,"val":"config","end":""},{"old":"/api/config/mapbox","type":0,"val":"mapbox","end":""}],
    types: placeholder as Registry['mapbox.token']['types'],
  },
  'moderator.moderator.store_comunicado': {
    methods: ["POST"],
    pattern: '/api/moderator/comunicados',
    tokens: [{"old":"/api/moderator/comunicados","type":0,"val":"api","end":""},{"old":"/api/moderator/comunicados","type":0,"val":"moderator","end":""},{"old":"/api/moderator/comunicados","type":0,"val":"comunicados","end":""}],
    types: placeholder as Registry['moderator.moderator.store_comunicado']['types'],
  },
  'moderator.moderator.my_comunicados': {
    methods: ["GET","HEAD"],
    pattern: '/api/moderator/comunicados',
    tokens: [{"old":"/api/moderator/comunicados","type":0,"val":"api","end":""},{"old":"/api/moderator/comunicados","type":0,"val":"moderator","end":""},{"old":"/api/moderator/comunicados","type":0,"val":"comunicados","end":""}],
    types: placeholder as Registry['moderator.moderator.my_comunicados']['types'],
  },
  'moderator.moderator.drivers_list': {
    methods: ["GET","HEAD"],
    pattern: '/api/moderator/drivers',
    tokens: [{"old":"/api/moderator/drivers","type":0,"val":"api","end":""},{"old":"/api/moderator/drivers","type":0,"val":"moderator","end":""},{"old":"/api/moderator/drivers","type":0,"val":"drivers","end":""}],
    types: placeholder as Registry['moderator.moderator.drivers_list']['types'],
  },
  'moderator.moderator.inactive_drivers': {
    methods: ["GET","HEAD"],
    pattern: '/api/moderator/drivers/inactive',
    tokens: [{"old":"/api/moderator/drivers/inactive","type":0,"val":"api","end":""},{"old":"/api/moderator/drivers/inactive","type":0,"val":"moderator","end":""},{"old":"/api/moderator/drivers/inactive","type":0,"val":"drivers","end":""},{"old":"/api/moderator/drivers/inactive","type":0,"val":"inactive","end":""}],
    types: placeholder as Registry['moderator.moderator.inactive_drivers']['types'],
  },
  'moderator.moderator.notify_driver': {
    methods: ["POST"],
    pattern: '/api/moderator/drivers/:id/notify',
    tokens: [{"old":"/api/moderator/drivers/:id/notify","type":0,"val":"api","end":""},{"old":"/api/moderator/drivers/:id/notify","type":0,"val":"moderator","end":""},{"old":"/api/moderator/drivers/:id/notify","type":0,"val":"drivers","end":""},{"old":"/api/moderator/drivers/:id/notify","type":1,"val":"id","end":""},{"old":"/api/moderator/drivers/:id/notify","type":0,"val":"notify","end":""}],
    types: placeholder as Registry['moderator.moderator.notify_driver']['types'],
  },
  'moderator.moderator.report_driver': {
    methods: ["POST"],
    pattern: '/api/moderator/drivers/:id/report',
    tokens: [{"old":"/api/moderator/drivers/:id/report","type":0,"val":"api","end":""},{"old":"/api/moderator/drivers/:id/report","type":0,"val":"moderator","end":""},{"old":"/api/moderator/drivers/:id/report","type":0,"val":"drivers","end":""},{"old":"/api/moderator/drivers/:id/report","type":1,"val":"id","end":""},{"old":"/api/moderator/drivers/:id/report","type":0,"val":"report","end":""}],
    types: placeholder as Registry['moderator.moderator.report_driver']['types'],
  },
  'moderator.moderator.store_encuesta': {
    methods: ["POST"],
    pattern: '/api/moderator/encuestas',
    tokens: [{"old":"/api/moderator/encuestas","type":0,"val":"api","end":""},{"old":"/api/moderator/encuestas","type":0,"val":"moderator","end":""},{"old":"/api/moderator/encuestas","type":0,"val":"encuestas","end":""}],
    types: placeholder as Registry['moderator.moderator.store_encuesta']['types'],
  },
  'moderator.moderator.encuesta_results': {
    methods: ["GET","HEAD"],
    pattern: '/api/moderator/encuestas/:id/results',
    tokens: [{"old":"/api/moderator/encuestas/:id/results","type":0,"val":"api","end":""},{"old":"/api/moderator/encuestas/:id/results","type":0,"val":"moderator","end":""},{"old":"/api/moderator/encuestas/:id/results","type":0,"val":"encuestas","end":""},{"old":"/api/moderator/encuestas/:id/results","type":1,"val":"id","end":""},{"old":"/api/moderator/encuestas/:id/results","type":0,"val":"results","end":""}],
    types: placeholder as Registry['moderator.moderator.encuesta_results']['types'],
  },
  'moderator.moderator.answer_encuesta': {
    methods: ["POST"],
    pattern: '/api/moderator/encuestas/:id/answer',
    tokens: [{"old":"/api/moderator/encuestas/:id/answer","type":0,"val":"api","end":""},{"old":"/api/moderator/encuestas/:id/answer","type":0,"val":"moderator","end":""},{"old":"/api/moderator/encuestas/:id/answer","type":0,"val":"encuestas","end":""},{"old":"/api/moderator/encuestas/:id/answer","type":1,"val":"id","end":""},{"old":"/api/moderator/encuestas/:id/answer","type":0,"val":"answer","end":""}],
    types: placeholder as Registry['moderator.moderator.answer_encuesta']['types'],
  },
  'avisos.moderator.avisos_index': {
    methods: ["GET","HEAD"],
    pattern: '/api/avisos',
    tokens: [{"old":"/api/avisos","type":0,"val":"api","end":""},{"old":"/api/avisos","type":0,"val":"avisos","end":""}],
    types: placeholder as Registry['avisos.moderator.avisos_index']['types'],
  },
  'avisos.moderator.avisos_store': {
    methods: ["POST"],
    pattern: '/api/avisos',
    tokens: [{"old":"/api/avisos","type":0,"val":"api","end":""},{"old":"/api/avisos","type":0,"val":"avisos","end":""}],
    types: placeholder as Registry['avisos.moderator.avisos_store']['types'],
  },
  'avisos.moderator.avisos_pin': {
    methods: ["PUT"],
    pattern: '/api/avisos/:id/pin',
    tokens: [{"old":"/api/avisos/:id/pin","type":0,"val":"api","end":""},{"old":"/api/avisos/:id/pin","type":0,"val":"avisos","end":""},{"old":"/api/avisos/:id/pin","type":1,"val":"id","end":""},{"old":"/api/avisos/:id/pin","type":0,"val":"pin","end":""}],
    types: placeholder as Registry['avisos.moderator.avisos_pin']['types'],
  },
  'avisos.moderator.avisos_delete': {
    methods: ["DELETE"],
    pattern: '/api/avisos/:id',
    tokens: [{"old":"/api/avisos/:id","type":0,"val":"api","end":""},{"old":"/api/avisos/:id","type":0,"val":"avisos","end":""},{"old":"/api/avisos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['avisos.moderator.avisos_delete']['types'],
  },
  'emergency.trigger': {
    methods: ["POST"],
    pattern: '/api/emergency',
    tokens: [{"old":"/api/emergency","type":0,"val":"api","end":""},{"old":"/api/emergency","type":0,"val":"emergency","end":""}],
    types: placeholder as Registry['emergency.trigger']['types'],
  },
  'leader.leader.avisos_index': {
    methods: ["GET","HEAD"],
    pattern: '/api/leader/avisos',
    tokens: [{"old":"/api/leader/avisos","type":0,"val":"api","end":""},{"old":"/api/leader/avisos","type":0,"val":"leader","end":""},{"old":"/api/leader/avisos","type":0,"val":"avisos","end":""}],
    types: placeholder as Registry['leader.leader.avisos_index']['types'],
  },
  'leader.leader.avisos_store': {
    methods: ["POST"],
    pattern: '/api/leader/avisos',
    tokens: [{"old":"/api/leader/avisos","type":0,"val":"api","end":""},{"old":"/api/leader/avisos","type":0,"val":"leader","end":""},{"old":"/api/leader/avisos","type":0,"val":"avisos","end":""}],
    types: placeholder as Registry['leader.leader.avisos_store']['types'],
  },
  'leader.leader.avisos_pin': {
    methods: ["PUT"],
    pattern: '/api/leader/avisos/:id/pin',
    tokens: [{"old":"/api/leader/avisos/:id/pin","type":0,"val":"api","end":""},{"old":"/api/leader/avisos/:id/pin","type":0,"val":"leader","end":""},{"old":"/api/leader/avisos/:id/pin","type":0,"val":"avisos","end":""},{"old":"/api/leader/avisos/:id/pin","type":1,"val":"id","end":""},{"old":"/api/leader/avisos/:id/pin","type":0,"val":"pin","end":""}],
    types: placeholder as Registry['leader.leader.avisos_pin']['types'],
  },
  'leader.leader.avisos_delete': {
    methods: ["DELETE"],
    pattern: '/api/leader/avisos/:id',
    tokens: [{"old":"/api/leader/avisos/:id","type":0,"val":"api","end":""},{"old":"/api/leader/avisos/:id","type":0,"val":"leader","end":""},{"old":"/api/leader/avisos/:id","type":0,"val":"avisos","end":""},{"old":"/api/leader/avisos/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['leader.leader.avisos_delete']['types'],
  },
  'leader.leader.store_comunicado': {
    methods: ["POST"],
    pattern: '/api/leader/comunicados',
    tokens: [{"old":"/api/leader/comunicados","type":0,"val":"api","end":""},{"old":"/api/leader/comunicados","type":0,"val":"leader","end":""},{"old":"/api/leader/comunicados","type":0,"val":"comunicados","end":""}],
    types: placeholder as Registry['leader.leader.store_comunicado']['types'],
  },
  'leader.leader.my_comunicados': {
    methods: ["GET","HEAD"],
    pattern: '/api/leader/comunicados',
    tokens: [{"old":"/api/leader/comunicados","type":0,"val":"api","end":""},{"old":"/api/leader/comunicados","type":0,"val":"leader","end":""},{"old":"/api/leader/comunicados","type":0,"val":"comunicados","end":""}],
    types: placeholder as Registry['leader.leader.my_comunicados']['types'],
  },
  'leader.leader.drivers_list': {
    methods: ["GET","HEAD"],
    pattern: '/api/leader/drivers',
    tokens: [{"old":"/api/leader/drivers","type":0,"val":"api","end":""},{"old":"/api/leader/drivers","type":0,"val":"leader","end":""},{"old":"/api/leader/drivers","type":0,"val":"drivers","end":""}],
    types: placeholder as Registry['leader.leader.drivers_list']['types'],
  },
  'leader.leader.reports_limited': {
    methods: ["GET","HEAD"],
    pattern: '/api/leader/reports',
    tokens: [{"old":"/api/leader/reports","type":0,"val":"api","end":""},{"old":"/api/leader/reports","type":0,"val":"leader","end":""},{"old":"/api/leader/reports","type":0,"val":"reports","end":""}],
    types: placeholder as Registry['leader.leader.reports_limited']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
